# Generated by Django 5.1.3 on 2025-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pno', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=255)),
                ('pdescription', models.TextField(blank=True, null=True)),
                ('pqt', models.IntegerField(default=0)),
                ('pimg', models.ImageField(upload_to='product_images/')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdiscpri', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
