# Generated by Django 5.1.3 on 2025-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_about_provide'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
