# Generated by Django 5.1.3 on 2025-02-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category'),
        ),
    ]
