# Generated by Django 5.1.3 on 2025-02-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_product_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cate',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category'),
        ),
    ]
