# Generated by Django 5.1.3 on 2025-02-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_product_cate_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cate',
        ),
    ]
