# Generated by Django 5.1.3 on 2025-02-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_category_product_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cate',
        ),
    ]
