# Generated by Django 5.1.3 on 2025-02-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_product_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pno', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=255)),
                ('pdescription', models.TextField(blank=True, null=True)),
                ('pqt', models.IntegerField(default=0)),
                ('pimg', models.ImageField(upload_to='product_images/')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdiscpri', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
