# Generated by Django 5.1.3 on 2025-02-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_products_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
